name: CI on Xamarin Android project
on: push
jobs:
  build:
  
    runs-on: macos-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v1

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build Android project
      run: |
        cd AwesomeXamarinApp
        cd AwesomeXamarinApp.Android
        msbuild AwesomeXamarinApp.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Debug 

    - name: Obtain Android APK file
      uses: actions/upload-artifact@v2
      with:
        name: Xamarin Awesome App
        path: AwesomeXamarinApp/AwesomeXamarinApp.Android/bin/Debug/com.companyname.awesomexamarinapp-Signed.apk
